[tool.poetry]
name = "renovate-b"
version = "0.1.0"
description = ""
authors = ["Brian"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = { version = "^0.112.0", optional = true }
